"""
Configuration package for Pregame Client Discovery Engine
"""

from .settings import (
    DEFAULT_SEARCH_SETTINGS,
    DEFAULT_QUALIFICATION_SETTINGS,
    CLIENT_LIMITS,
    SUPPORTED_CLIENT_TYPES,
    DEFAULT_API_SETTINGS,
    LIVE_UPDATE_SETTINGS,
    REPORT_SETTINGS
)

__all__ = [
    'DEFAULT_SEARCH_SETTINGS',
    'DEFAULT_QUALIFICATION_SETTINGS',
    'CLIENT_LIMITS',
    'SUPPORTED_CLIENT_TYPES',
    'DEFAULT_API_SETTINGS',
    'LIVE_UPDATE_SETTINGS',
    'REPORT_SETTINGS'
] 